# Generated by Django 5.2.3 on 2025-07-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='event_asset/defaultpng.png', null=True, upload_to='event_asset'),
        ),
    ]
